[package]
name = "gobject-example"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
once_cell = "1.0"

[lib]
crate-type = ["cdylib"]

[features]
bindings = []
